# Generated by Django 5.0.4 on 2024-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo12app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='yourmessage',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
